export const All_PRODUCT_REQUEST = 'All_PRODUCT_REQUEST'
export const All_PRODUCT_SUCCESS = 'All_PRODUCT_SUCCESS'
export const All_PRODUCT_FAIL = 'All_PRODUCT_FAIL'

export const PRODUCT_DETAIL_REQUEST = 'PRODUCT_DETAIL_REQUEST'
export const PRODUCT_DETAIL_SUCCESS = 'PRODUCT_DETAIL_SUCCESS'
export const PRODUCT_DETAIL_FAIL = 'PRODUCT_DETAIL_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'